
services:
  postgres:
    image: postgres:15-alpine
    container_name: bank_queue_db
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpassword123
      POSTGRES_DB: bank_queue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/database/postgres/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - bank_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser -d bank_queue"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: bank_queue_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bank.ru
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bank_network
    depends_on:
      - postgres
    restart: unless-stopped

  # Твой Go-сервер
  bank_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: bankuser
      DB_PASSWORD: bankpassword123
      DB_NAME: bank_queue
      DB_SSLMODE: disable
      SERVER_PORT: 8080
    networks:
      - bank_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    name: bank_queue_postgres_data
  pgadmin_data:
    name: bank_queue_pgadmin_data

networks:
  bank_network:
    name: bank_queue_network
    driver: bridge